name: arkit_plugin
description: Flutter Plugin for ARKit - Apple's augmented reality (AR) development platform for iOS mobile devices.
version: 1.0.6
homepage: https://github.com/olexale/arkit_flutter_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  vector_math: ^2.1.4
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ArkitPlugin
